### ISSUE TITLE
Can't use firefox impersolate

### ISSUE THREAD

**Issue by Loclhost** [yifeikong/curl_cffi#177] opened 2023-12-16 07:13 UTC
**Describe the bug**
Can't use any impersolate for Firefox

**To Reproduce**
```
r = requests.get("https://tls.browserleaks.com/json",
                 impersonate="ff102",
                 proxies=proxies,
                 headers = header)
```

**Expected behavior**
Expect some JA3 hash for firefox

**Versions**
 - OS: Windows 11
cffi==1.16.0
curl-cffi==0.5.10
dpkt==1.9.8
pycparser==2.21
pyja3==1.0.0

**Additional context**
- Sync session

Error 
    raise RequestsError(f"impersonate {impersonate} is not supported")
curl_cffi.requests.errors.RequestsError: impersonate ff102 is not supported

**Comment by T-256** [comment] 2023-12-16 07:31
duplicate of https://github.com/yifeikong/curl_cffi/issues/59

**Comment by yifeikong** [comment] 2024-01-01 04:01
Close as dup of #59

**Closed by yifeikong** 2024-01-01 04:01 UTC
Labels: enhancement
