### ISSUE TITLE
Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 1 was not closed cleanly before end of the underlying stream'

### ISSUE THREAD

**Issue by mstplm** [yifeikong/curl_cffi#42] opened 2023-04-09 21:39 UTC
大佬，我的python是3.8，curl_cuff版本是0.5.3，目前用GET请求并发抓取部分网站会出现如下报错：
Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 1 was not closed cleanly before end of the underlying stream'。而且时间久了会导致程序直接卡死，可以查找一下原因吗

**Comment by yifeikong** [comment] 2023-04-12 12:58
Duplicate of #19

**Comment by merry75** [comment] 2023-04-13 21:49
no still happens

**Comment by yifeikong** [comment] 2023-04-14 00:38
@merry75 Do you mean it still happens after removing `Content-Length` header?

**Comment by yifeikong** [comment] 2023-04-15 02:33
Were you using proxies? Low quality proxies can also be a cause.
用代理了吗？低质代理也可能引起这个问题。

**Closed** 2023-05-23 05:03 UTC
Labels: duplicate
