### ISSUE TITLE
[BUG] 0.6.3 can't build on RaspiOS (Raspberry Pi 4)

### ISSUE THREAD

**Issue by FRIKIdelTO** [yifeikong/curl_cffi#306] opened 2024-04-25 06:50 UTC
**Describe the bug**
```frikidelto@rpi-1:~ $ pip install curl_cffi --no-cache-dir
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting curl_cffi
  Downloading curl_cffi-0.6.3.tar.gz (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 kB 4.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "/home/frikidelto/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/frikidelto/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/frikidelto/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 307, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 658, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 678, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-7mluy19s/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "scripts/build.py", line 45, in <module>
          arch = detect_arch()
        File "scripts/build.py", line 42, in detect_arch
          raise Exception(f"Unsupported arch: {uname}")
      Exception: Unsupported arch: uname_result(system='Linux', node='rpi-1', release='6.1.21-v8+', version='#1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023', machine='aarch64')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**To Reproduce**
```
pip install curl_cffi
```

**Versions**
```
uname -a
Linux rpi-1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

python --version
Python 3.9.2

pip freeze
amazoncaptcha==0.5.11
appdirs==1.4.4
arandr==0.1.10
astroid==2.5.1
asttokens==2.0.4
async-generator==1.10
attrs==23.2.0
automationhat==0.2.0
beautifulsoup4==4.12.3
behave==1.2.6
bitlyshortener==0.6.4
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
cachetools==5.3.1
Cap1xxx==0.1.3
certifi==2023.11.17
chardet==5.2.0
charset-normalizer==3.3.2
click==7.1.2
colorama==0.4.6
colorzero==1.1
contourpy==1.0.7
cryptography==3.3.2
cssselect==1.2.0
cupshelpers==1.0
cycler==0.11.0
dbus-python==1.2.16
distro==1.5.0
docutils==0.16
drumhat==0.1.0
EasyProcess==1.1
entrypoint2==1.1
envirophat==1.0.0
exceptiongroup==1.2.0
execnet==2.0.2
ExplorerHAT==0.4.2
facebook-sdk==3.1.0
fasteners==0.19
filelock==3.13.1
Flask==1.1.2
fonttools==4.39.4
fourletterphat==0.1.0
google-api-core==2.11.0
google-api-python-client==2.109.0
google-auth==2.19.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.1.0
googleapis-common-protos==1.59.0
gpiozero==2.0
h11==0.14.0
html5lib==1.1
httplib2==0.22.0
idna==3.6
imagekitio==3.2.0
importlib-metadata==6.6.0
importlib-resources==5.12.0
iniconfig==2.0.0
isort==5.6.4
itsdangerous==1.1.0
jedi==0.18.0
jeepney==0.8.0
Jinja2==2.11.3
kiwisolver==1.4.4
lazy-object-proxy==0.0.0
logilab-common==1.8.1
lxml==4.6.3
markdown-it-py==3.0.0
MarkupSafe==1.1.1
matplotlib==3.8.2
mccabe==0.6.1
mdurl==0.1.2
microdotphat==0.2.1
mote==0.0.4
motephat==0.0.3
MouseInfo==0.1.3
mss==9.0.1
mypy==0.812
mypy-extensions==0.4.3
numpy==1.26.2
oauthlib==3.2.2
outcome==1.3.0.post0
packaging==23.2
pantilthat==0.0.7
parameterized==0.9.0
parse==1.20.0
parse-type==0.6.2
parso==0.8.1
pdbp==1.5.0
pexpect==4.8.0
pgzero==1.2
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picamera2==0.3.9
pidng==4.0.9
piexif==1.1.3
piglow==1.2.5
pigpio==1.78
Pillow==9.5.0
platformdirs==4.1.0
pluggy==1.3.0
protobuf==4.23.2
psutil==5.9.6
py==1.11.0
pyaes==1.6.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
PyAutoGUI==0.9.54
pycairo==1.16.2
pycups==2.0.1
pyee==8.2.2
pygame==1.9.6
PyGetWindow==0.0.9
Pygments==2.17.2
PyGObject==3.38.0
pyinotify==0.9.6
PyJWT==1.7.1
pylint==2.7.2
PyMsgBox==1.0.9
pynose==1.4.8
PyOpenGL==3.1.5
pyOpenSSL==20.0.1
pyotp==2.9.0
pyparsing==3.0.9
pyperclip==1.8.2
pyppeteer==1.0.2
pyppeteer-stealth==2.7.4
PyQt5==5.15.2
PyQt5-sip==12.8.1
PyRect==0.2.0
pyscreenshot==3.1
PyScreeze==0.1.29
pyserial==3.5b0
pysmbc==1.0.23
PySocks==1.7.1
pyTelegramBotAPI==4.14.0
pytest==7.4.4
pytest-html==2.0.1
pytest-metadata==3.0.0
pytest-ordering==0.6
pytest-rerunfailures==13.0
pytest-xdist==3.5.0
python-amazon-paapi==5.0.1
python-apt==2.2.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-prctl==1.7
python-wordpress-xmlrpc==2.3
python3-xlib==0.15
pytweening==1.0.7
PyYAML==6.0.1
rainbowhat==0.1.0
reportlab==3.5.59
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
responses==0.12.1
rich==13.7.0
roman==2.0.0
RPi.GPIO==0.7.0
rsa==4.9
RTIMULib==7.2.1
sbvirtualdisplay==1.3.0
scrollphat==0.0.7
scrollphathd==1.2.1
selenium==4.16.0
seleniumbase==4.22.6
Send2Trash==1.6.0b1
sense-hat==2.4.0
simplejpeg==1.6.4
simplejson==3.17.2
six==1.16.0
skywriter==0.0.7
sn3218==1.2.7
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
SpeechRecognition==3.10.1
spidev==3.5
ssh-import-id==5.10
tabcompleter==1.3.0
Telethon==1.33.0
thonny==4.0.1
toml==0.10.1
tomli==2.0.1
touchphat==0.0.1
tqdm==4.65.0
trio==0.24.0
trio-websocket==0.11.1
tweepy==4.14.0
twitter-text-parser==3.0.0
twython==3.8.2
typed-ast==1.4.2
typing-extensions==3.7.4.3
undetected-chromedriver==3.5.4
unicornhathd==0.0.4
uritemplate==4.1.1
urllib3==1.26.18
v4l2-python3==0.3.2
webdriver-manager==4.0.1
webencodings==0.5.1
websockets==10.4
Werkzeug==1.0.1
wrapt==1.12.1
wsproto==1.2.0
zipp==3.15.0
```

**Comment by yifeikong** [comment] 2024-04-25 07:51
Duplicate of #304, see updates there, please.

**Closed by yifeikong** 2024-04-25 07:51 UTC
Labels: bug
