### ISSUE TITLE
Add custom JA3

### ISSUE THREAD

**Issue by staz9** [yifeikong/curl_cffi#244] opened 2024-02-10 08:36 UTC
Can't we add our own ja3 string? These default ones are over used and easily detectable as their ja3 remain same.

**Comment by novitae** [comment] 2024-02-10 20:31
I know we are all waiting for this lol but there's also an issue about this https://github.com/yifeikong/curl_cffi/issues/194

**Comment by yifeikong** [comment] 2024-02-15 02:19
Duplicate of #194.

**Closed by yifeikong** 2024-02-15 02:19 UTC
Labels: bug
