### ISSUE TITLE
[BUG] Proxies being mismatched on AsyncSession requests

### ISSUE THREAD

**Issue by sc0ned** [yifeikong/curl_cffi#41] opened 2023-04-09 09:28 UTC
Hey again, found another weird bug. You'll need a list of proxies to reproduce (@yifeikong  - I can send you some on like tg or w/e if needed), but basically it seems that after the first request on each instance of the AsyncSession, they all start to use the first instance's proxy. It's probably best explained by example, so here's some code and what it output for me:

```py
from curl_cffi import requests
import json, asyncio
from collections import OrderedDict
from itertools import cycle

with open('proxy_list.txt', 'r') as temp_file:
	proxies = list(OrderedDict.fromkeys([line.rstrip('\n') for line in temp_file]))

formatted_proxies = []
for prox in proxies:
	splitted = prox.split(':')
	formatted_proxies.append(f"http://{splitted[2]}:{splitted[3]}@{splitted[0]}:{splitted[1]}")
proxy_pool = cycle(formatted_proxies)

async def test():
	async def do_req(sess, proxy):
		session_proxies = {"https":proxy,"http":proxy}
		r = await sess.get("https://httpbin.org/ip", proxies=session_proxies, impersonate="chrome110")
		proxy_1 = r.json()['origin']
		r = await sess.get("https://httpbin.org/ip", proxies=session_proxies, impersonate="chrome110")
		proxy_2 = r.json()['origin']
		return proxy_1, proxy_2
	
	tasks = []
	async with requests.AsyncSession() as s:
		for i in range(5):
			p = next(proxy_pool)
			tasks.append(do_req(s, p))
		results = await asyncio.gather(*tasks)
	print("RESULTS:")
	i = 0
	for res in results:
		i += 1
		print(f"#{str(i)}: 1st Request: {str(res[0])} | 2nd Request: {str(res[1])}")

policy = asyncio.WindowsSelectorEventLoopPolicy()
asyncio.set_event_loop_policy(policy)
asyncio.get_event_loop().run_until_complete(test())
```

Running this code produces output that looks something like:
```RESULTS:
#1: 1st Request: XXX.XXX.82.225 | 2nd Request: XXX.XXX.82.225
#2: 1st Request: XXX.XXX.92.220 | 2nd Request: XXX.XXX.82.225
#3: 1st Request: XXX.XXX.95.128 | 2nd Request: XXX.XXX.82.225
#4: 1st Request: XXX.XXX.83.56 | 2nd Request: XXX.XXX.82.225
#5: 1st Request: XXX.XXX.87.59 | 2nd Request: XXX.XXX.82.225
```

As you can see, the first request on each instance uses the correct proxy, but the second request always uses the first instance's proxy. Any idea what might be happening?

Python version: 3.9.6
curl_cffi version: 0.5.2 (getting the error code 60 issue that we're already discussing in another thread on 0.5.3 so I downgraded for now)
cffi version: 1.15.1

_Note after some more testing:_
If you create a new AsyncSession for every iteration rather than use it as a context manager, the problem doesn't occur and the second request will use the same proxy as the first (see code below)
```
for i in range(5):
	p = next(proxy_pool)
	tasks.append(do_req(requests.AsyncSession(), p))
results = await asyncio.gather(*tasks)
```

**Comment by yifeikong** [comment] 2023-04-11 16:11
> As you can see, the first request on each instance uses the correct proxy, but the second request always uses the first instance's proxy. Any idea what might be happening?

I'm still not sure what's wrong under the hood. It seems that different requests are reusing un-reset curl instances, but I can not reproduce it, even on 0.5.2.

> If you create a new AsyncSession for every iteration rather than use it as a context manager, the problem doesn't occur and the second request will use the same proxy as the first (see code below)

For each AsyncSession, a lifo queue of curl instances is created, if you are using different sessions for different coroutines, it's guaranteed that the requests make in each coroutine will not share the same curl instance.

**Comment by yifeikong** [comment] 2023-04-11 16:16
Could you please try using 0.5.3 with `session.get(..., verify=False)` to see if this still persists?

**Comment by yifeikong** [comment] 2023-04-12 14:00
I found an exact same [issue](https://github.com/guzzle/guzzle/issues/2257) as you described, which is unfortunately left unanswered... My current guess is curl_multi will mess up when reusing proxified connections.

However, There are two options we can add to avoid this issue, `CURLOPT_FRESH_CONNECT` and `CURLOPT_FORBID_REUSE`.

By using either of these options, a new connection will be created for each request, which is not suitable for normal requests because of the performance drain, but for crawling websites with proxies in bulk, it does not add more overhead since we are using different proxies already.

**Comment by yifeikong** [comment] 2023-04-14 01:18
@jjsaunier I see your points here. When using sessions, I presume two things are handled automatically:

1. Cookies are set and send like browsers.
2. Connections are cached and reused.

If we were not using proxies, the situation is simpler and there is no ambiguity. But with proxies, should the connection be considered the same if they share

1. the same `host`, or
2. the same `host` + `proxy`

I'm not sure what requests or httpx implement `Session.request(..., proxies=...)`, which, I think, is how most users would expect to happen.

**Comment by yifeikong** [comment] 2023-04-14 10:27
I just checked both [requests](https://requests.readthedocs.io/en/latest/api/#requests.Session.request) and [httpx](https://www.python-httpx.org/api/#asyncclient)'s docs. It turns out that they do differ on this matter.

For httpx, there is no `proxies` parameter for `Client.request`. You can only set proxies when initializing the Client instance, which is the way @jjsaunier suggested.

> `async request(self, method, url, *, content=None, data=None, files=None, json=None, params=None, headers=None, cookies=None, auth=, follow_redirects=, timeout=, extensions=None)`
> No proxies here.

For requests, it does support mutating proxies in the context of a session, and it behaves as expected.

> `request(method, url, params=None, data=None, headers=None, cookies=None, files=None, auth=None, timeout=None, allow_redirects=True, proxies=None, hooks=None, stream=None, verify=None, cert=None, json=None)`

I did a little experiment to verify it.

<details>
<summary><b>Details</b></summary>

```
brew install tinyproxy

cat proxy1.conf

Port 8964
Listen 127.0.0.1
Timeout 601
Allow 127.0.0.1
AddHeader "X-Proxy" "alpha"

cat proxy2.conf

Port 8965
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
AddHeader "X-Proxy" "beta"

tinyproxy -d -c proxy1.conf
tinyproxy -d -c proxy2.conf
```

Two proxies listening on two different ports and add two different header to distinguish from each other.

```py
import requests

s = requests.Session()

r = s.get("http://httpbin.org/headers", proxies={"http": "http://localhost:8964"})
print(r.json())

r = s.get("http://httpbin.org/headers", proxies={"http": "http://localhost:8965"})
print(r.json())

s.close()
```

Results:

```
{'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.28.2', 'X-Amzn-Trace-Id': 'Root=1-643919ef-5dbdc737332d075e3057c7a8', 'X-Proxy': 'alpha'}}
{'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.28.2', 'X-Amzn-Trace-Id': 'Root=1-643919f0-3b710d137382a925180be5a8', 'X-Proxy': 'beta'}}
```

It's also the same behavior if you use `curl_cffi.requests`.
</details>

**Comment by jjsaunier** [comment] 2023-04-14 12:22
Yes, both approaches are acceptable,  strict vs. relaxed. The relaxed one has some downsides explained below

Additionally to automatic stuff, the hop-by-hop header `Connection` must be set to `keep-alive` to tell the next hop to keep the connection open instead of closing after the response.

I think session + proxy change should not be possible, adding `cookie_jar` on request (where each request can reuse this jar to keep and retrieve cookies from it) and not enabling proxy mutation while in session. It's still easy to control cookies. It also avoids keeping a lot of connections (the kernel will or the upstream will timeout them via `/proc/sys/net/ipv4/tcp_keepalive_time`) - each proxy mutation will open a new keep-alive connection (at the library level, there is no way to know if the user will issue more request with the same proxy or mutate it to close the previous)

**Comment by yifeikong** [comment] 2023-06-28 11:59
I was planning to take another look at this, but somehow it's gone. I tested it on the latest version 0.5.6, and it seems that the issue no longer exists. My guess is that the "reset curl options" behavior introduced in previous version is the fix.

Anyway, here is my test script and result, feel free to reopen this if it still persists on your side.

```
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:19 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#2: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#3: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
#4: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
#5: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:29 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
#2: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#3: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
#4: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#5: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:38 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
#2: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#3: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#4: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
#5: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:40 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
#2: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
#3: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#4: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#5: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:48 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#2: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#3: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
#4: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
#5: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
┬─[ubuntu@VM-0-10-ubuntu:~/repos]─[07:44:50 PM]
╰─>$ python aio_mis.py                                                                                                                                                                                                                                                                                                                                                (curl) 
RESULTS:
#1: 1st Request: 172.104.171.218 | 2nd Request: 172.104.171.218
#2: 1st Request: 192.53.112.75 | 2nd Request: 192.53.112.75
#3: 1st Request: 172.104.163.28 | 2nd Request: 172.104.163.28
#4: 1st Request: 172.104.62.95 | 2nd Request: 172.104.62.95
#5: 1st Request: 172.104.48.37 | 2nd Request: 172.104.48.37
```

script

```python
import asyncio                                                                         
from curl_cffi import requests                                                         
from itertools import cycle                                                            
import random                                                                          
                                                                                       
with open("proxy_list.txt", "r") as temp_file:                                         
    proxies = [line.rstrip("\n") for line in temp_file]                                
    random.shuffle(proxies)                                                            
                                                                                       
# print(proxies)                                                                       
                                                                                       
proxy_pool = cycle(proxies)                                                            
                                                                                       
                                                                                       
async def test():                                                                      
    async def do_req(sess, proxy):                                                     
        session_proxies = {"https": proxy, "http": proxy}                              
        r = await sess.get("https://ipinfo.io/", proxies=session_proxies)              
        # print(proxy, r.text)                                                         
        proxy_1 = r.json()["ip"]                                                       
        r = await sess.get("https://ipinfo.io/", proxies=session_proxies)              
        # print(proxy, r.text)                                                         
        proxy_2 = r.json()["ip"]                                                       
        return proxy_1, proxy_2                                                        
                                                                                       
    tasks = []                                                                         
    async with requests.AsyncSession() as s:                                           
        for i in range(5):                                                             
            p = next(proxy_pool)                                                       
            # p = random.choice(proxies)                                               
            tasks.append(do_req(s, p))                                                 
        results = await asyncio.gather(*tasks)                                         
    print("RESULTS:")                                                                  
    i = 0                                                                              
    for res in results:                                                                
        i += 1                                                                         
        print(f"#{str(i)}: 1st Request: {str(res[0])} | 2nd Request: {str(res[1])}")   
                                                                                       
                                                                                       
asyncio.run(test())                                                                    
```

**Closed by yifeikong** 2023-06-28 11:59 UTC
Labels: bug, help wanted
