### ISSUE TITLE
Cookies are lost between GET and POST requests in a session

### ISSUE THREAD

**Issue by mobti100** [yifeikong/curl_cffi#83] opened 2023-07-14 23:19 UTC
I created a session and made some GET requests to harvest some cookies. Cookies were not lost during redirection but when I followed with a POST request using the same session, cookies were lost and I got bad request error.

As you can see below, we have some session cookies that are set in the first picture and but were not sent with the POST request as you can see in the second picture.
<img width="1374" alt="Screen Shot 2023-07-15 at 12 13 07 AM" src="https://github.com/yifeikong/curl_cffi/assets/137413814/18dab628-25a5-48bc-b9eb-8ac45c54f6c4">

<img width="1374" alt="Screen Shot 2023-07-15 at 12 11 06 AM" src="https://github.com/yifeikong/curl_cffi/assets/137413814/9a974a34-9617-46d2-a85a-d76f53f45867">

```python
from curl_cffi import requests
from bs4 import BeautifulSoup


s = requests.Session(
    impersonate='chrome101',
    proxies={
        'https': 'http://localhost:8888'
    },
    verify=False
)
s.get('https://visa-de.tlscontact.com/')
r = s.get('https://visa-de.tlscontact.com/oauth2/authorization/oidc')
soup = BeautifulSoup(r.text, 'lxml')
url = soup.find('form', id='kc-form-login').get('action')
s.post(
    url,
    data={
        'username': 'USERNAME',
        'password': 'PASSWORD'
    }
)
```

**Comment by yifeikong** [comment] 2023-07-15 20:57
Duplicate of #55

**Closed** 2023-08-06 08:53 UTC
