### ISSUE TITLE
Content-type header

### ISSUE THREAD

**Issue by mafuyuuu1** [yifeikong/curl_cffi#77] opened 2023-07-08 11:34 UTC
There's a bug on the `content-type` header that it doesn't override if you add it on your headers but it duplicates instead unlike, for example, the `user-agent` header. I don't know on other content-types but I only tested it in `requests.AsyncSession` with `content-type:application/json`

**Comment by yifeikong** [comment] 2023-07-08 13:01
Thanks for reporting this! I have been seeing people open json-related issues, but could not reproduce them. I guess this is the root cause. I will try to fix it ASAP.

**Comment by mafuyuuu1** [comment] 2023-07-09 06:05
Thank you so much!

**Comment by meliksahbozkurt** [comment] 2023-07-10 09:44
It seems like on Windows, using double quotes for -d parameter is required. (Here is detailed example https://stackoverflow.com/a/24499743)
But i couldn't find how to implement this spesification into curl_cffi.

**Comment by mafuyuuu1** [comment] 2023-07-10 09:52
> It seems like on Windows, using double quotes for -d parameter is required. (Here is detailed example https://stackoverflow.com/a/24499743)

You need to load it first on json by using `json.loads` to make it the same as this `"{\"key\":\"val\"}"`

**Comment by meliksahbozkurt** [comment] 2023-07-10 10:20
> > It seems like on Windows, using double quotes for -d parameter is required. (Here is detailed example https://stackoverflow.com/a/24499743)
> 
> You need to load it first on json by using `json.loads` in order to make `{"key":"val"}` the same as this `"{\"key\":\"val\"}"`
> 
> > i couldn't find how to implement this spesification into curl_cffi.
> 
> I think the module is doing it automatically so why do you worry about that?

If i specify Content-Type header, the module probably uses single quota and some of the websites raise Bad Request in this case. If i remove Content-Type, everything is all fine.

**Comment by mafuyuuu1** [comment] 2023-07-10 10:36
> If i specify Content-Type header, the module probably uses single quota and some of the websites raise Bad Request in this case. If i remove Content-Type, everything is all fine.


Ohhh.. This is what I'm saying on my report. You can't override the `content-type: application/json` for now for now until it is fixed. 

> the module probably uses single quota

This is the part that I don't understand. Can you show your MWE (Minimal working example)?

**Comment by meliksahbozkurt** [comment] 2023-07-10 11:08
> > the module probably uses single quota
> 
> This is the part that I don't understand. Can you show your MWE (Minimal working example)?


Sadly, i can't provide a MWE, but as i mentioned before the problem and solution explanied here: https://stackoverflow.com/a/24499743

I had a glance at the source code of curl_cffi but could not find any possibility to do a simple fix like changing single quota character into double quota.

**Comment by yifeikong** [comment] 2023-07-10 15:34
@meliksahbozkurt  I don't believe that you are referring to the same issue here. There is nothing to do with command line curl options. `curl_cffi` uses `libcurl` and does not interact with underlying curl via by passing cli arguments.

**Comment by yifeikong** [comment] 2023-11-02 11:40
This should have been fixed in 0.5.9.

**Closed by yifeikong** 2023-11-02 11:40 UTC
