### ISSUE TITLE
Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'

### ISSUE THREAD

**Issue by user-pppp** [yifeikong/curl_cffi#287] opened 2024-04-02 09:06 UTC
Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/curl_cffi/requests/session.py", line 391, in request
    c.perform()
  File "/usr/local/lib64/python3.9/site-packages/curl_cffi/curl.py", line 187, in perform
    self._check_error(ret, action="perform")
  File "/usr/local/lib64/python3.9/site-packages/curl_cffi/curl.py", line 80, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/python/worker/LFBeeworker3/tools/s6eweb_flights_cache_builder.py", line 294, in creat_token
    response = session.post(
  File "/usr/local/lib64/python3.9/site-packages/curl_cffi/requests/session.py", line 393, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'

pip3 show curl_cffi
Name: curl-cffi
Version: 0.5.2

**Comment by yifeikong** [comment] 2024-04-02 09:07
Duplicate of #165

**Closed by yifeikong** 2024-04-02 09:07 UTC
Labels: bug

**Comment by user-pppp** [comment] 2024-04-02 11:37
感谢
